version: '3.8'
services:
  test-stimulus:
    build: test-stimulus
    volumes:
      - ../code:/var/www/html/test-stimulus
  nginxx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../code:/var/www/html/test-stimulus
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - test-stimulus
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test-stimulus
      - MYSQL_USER=stimulus_user
      - MYSQL_PASSWORD=1234
